#@TYPE: Machine
#@NAME: Seeed reComputer J40 Mini

MACHINEOVERRIDES =. "p3768-0000-p3767-0000:"
require conf/machine/p3768-0000-p3767-0000.conf
require conf/machine/include/seeed-orin-j401.inc

SEEED_DTB = "tegra234-j40mini-p3768-0000+p3767-0000-recomputer.dtb"
SEEED_PINMUX_CONFIG = "recomputer-mini-orin-j40-pinmux-p3767-0000.dtsi"
SEEED_PMC_CONFIG = "recomputer-mini-orin-j40-padvoltage-p3767-0000.dtsi"
SEEED_DCE_OVERLAY = ""
SEEED_OVERLAYS = ""
