#@TYPE: Machine
#@NAME: Seeed AGX Orin 64GB Kit

require conf/machine/include/agx-orin.inc
require conf/machine/include/seeed-agx-orin.inc

SEEED_DTB = "tegra234-p3737-0000+p3701-0000-seeed.dtb"
SEEED_PINMUX_CONFIG = "seeed-agx-orin-kit-mb1-bct-pinmux-p3701-0000.dtsi"
SEEED_PMC_CONFIG = "seeed-agx-orin-kit-mb1-bct-padvoltage-p3701-0000.dtsi"
SEEED_DCE_OVERLAY = ""
SEEED_OVERLAYS = ""
