#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd -- "$SCRIPT_DIR/../.." && pwd)

MACHINE=${MACHINE:-recomputer-orin-super-j401}
BUILD_DIR=${BUILD_DIR:-build-seeed}
CACHE_DIR=${CACHE_DIR:-${XDG_CACHE_HOME:-$HOME/.cache}/yocto-seeed}

usage() {
    cat <<EOF
Usage: $(basename "$0") [options]

Prepare a lightweight Seeed carrier-board Yocto build workspace.

Options:
  --build-dir DIR   Build directory relative to the repository or absolute
                    (default: $BUILD_DIR)
  --cache-dir DIR   Shared downloads/sstate directory
                    (default: $CACHE_DIR)
  --machine NAME    Yocto MACHINE (default: $MACHINE)
  --no-activate     Do not make this the active Seeed build workspace
  --no-submodules   Do not initialize/update git submodules
  --full-history    Fetch full submodule history instead of shallow clones
  -h, --help        Show this help

Environment variables MACHINE, BUILD_DIR, and CACHE_DIR provide the same
settings as the command-line options.
EOF
}

update_submodules=yes
shallow_submodules=yes
activate_workspace=yes
while [[ $# -gt 0 ]]; do
    case "$1" in
        --build-dir)
            BUILD_DIR=$2
            shift 2
            ;;
        --cache-dir)
            CACHE_DIR=$2
            shift 2
            ;;
        --machine)
            MACHINE=$2
            shift 2
            ;;
        --no-activate)
            activate_workspace=no
            shift
            ;;
        --no-submodules)
            update_submodules=no
            shift
            ;;
        --full-history)
            shallow_submodules=no
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown option: $1" >&2
            usage >&2
            exit 2
            ;;
    esac
done

for command in git bash awk sed readlink; do
    if ! command -v "$command" >/dev/null 2>&1; then
        echo "ERROR: required command not found: $command" >&2
        exit 1
    fi
done

if [[ ! -f "$REPO_ROOT/setup-env" || ! -f "$REPO_ROOT/.gitmodules" ]]; then
    echo "ERROR: run this script from a tegra-demo-distro source checkout." >&2
    exit 1
fi

if [[ $update_submodules == yes ]]; then
    echo "==> Initializing pinned source submodules"
    git -C "$REPO_ROOT" submodule sync --recursive
    if [[ $shallow_submodules == yes ]]; then
        git -C "$REPO_ROOT" submodule update --init --recursive --depth 1
    else
        git -C "$REPO_ROOT" submodule update --init --recursive
    fi
fi

mkdir -p "$CACHE_DIR/downloads" "$CACHE_DIR/sstate-cache"
CACHE_DIR=$(readlink -f "$CACHE_DIR")

if [[ $BUILD_DIR != /* ]]; then
    BUILD_DIR="$REPO_ROOT/$BUILD_DIR"
fi
BUILD_DIR=$(readlink -m "$BUILD_DIR")

if [[ -f $BUILD_DIR/conf/local.conf ]]; then
    configured_machine=$(awk -F'"' \
        '/^[[:space:]]*MACHINE[[:space:]]*(\?|\+|:)?=/{print $2; exit}' \
        "$BUILD_DIR/conf/local.conf")
    if [[ -n $configured_machine && $configured_machine != "$MACHINE" ]]; then
        echo "ERROR: build directory is configured for $configured_machine, not $MACHINE" >&2
        echo "Use a separate --build-dir for each machine." >&2
        exit 1
    fi
fi

echo "==> Creating/updating build configuration"
(
    cd "$REPO_ROOT"
    # setup-env is intentionally sourced because it exports the BitBake/OE
    # environment and changes into the selected build directory.
    # shellcheck disable=SC1091
    set +u
    . ./setup-env --machine "$MACHINE" "$BUILD_DIR"
    set -u

    configured_machine=$(sed -n 's/^[[:space:]]*MACHINE[[:space:]]*?=[[:space:]]*"\([^"]*\)".*/\1/p' \
        "$BUILDDIR/conf/local.conf" | head -n 1)
    if [[ -z $configured_machine ]]; then
        echo "ERROR: cannot determine MACHINE from $BUILDDIR/conf/local.conf" >&2
        exit 1
    fi
    if [[ $configured_machine != "$MACHINE" ]]; then
        cat >&2 <<EOF
ERROR: build directory is already configured for a different machine.
  Build dir:  $BUILDDIR
  Configured: $configured_machine
  Requested:  $MACHINE

Use a separate --build-dir for each Seeed carrier board.
EOF
        exit 1
    fi

    cache_conf="$BUILDDIR/conf/seeed-cache.conf"
    cat > "$cache_conf" <<EOF
# Generated by scripts/seeed/prepare-workspace.sh
DL_DIR = "$CACHE_DIR/downloads"
SSTATE_DIR = "$CACHE_DIR/sstate-cache"
BB_HASHSERVE_DB_DIR = "\${SSTATE_DIR}"
EOF

    include_line='require conf/seeed-cache.conf'
    if ! grep -Fxq "$include_line" "$BUILDDIR/conf/local.conf"; then
        printf '\n# Shared cache for Seeed carrier builds\n%s\n' "$include_line" >> "$BUILDDIR/conf/local.conf"
    fi
)

if [[ $activate_workspace == yes ]]; then
    active_file=$(git -C "$REPO_ROOT" rev-parse --git-path seeed-active-build)
    if [[ $active_file != /* ]]; then
        active_file="$REPO_ROOT/$active_file"
    fi
    mkdir -p "$(dirname "$active_file")"
    printf '%s\n' "$BUILD_DIR" > "$active_file"
fi

if [[ $activate_workspace == yes ]]; then
    next_build_args=
else
    printf -v next_build_args ' --build-dir %q' "$BUILD_DIR"
fi

cat <<EOF

Workspace prepared successfully.

  Repository: $REPO_ROOT
  Machine:    $MACHINE
  Build dir:  $BUILD_DIR
  Downloads:  $CACHE_DIR/downloads
  Sstate:     $CACHE_DIR/sstate-cache
  Active:     $activate_workspace

Next steps:
  $REPO_ROOT/scripts/seeed/build.sh current$next_build_args
  $REPO_ROOT/scripts/seeed/build.sh metadata$next_build_args
  $REPO_ROOT/scripts/seeed/build.sh dtb$next_build_args
  $REPO_ROOT/scripts/seeed/build.sh image$next_build_args
EOF
